### ISSUE TITLE
KRLS will not install without pre-requisite RSpectra

### ISSUE THREAD

**Issue by aaronrudkin** [lukesonnet/KRLS#1]
Try to install KRLS on a Windows machine without RSpectra installed; this will fail silently. 

Install RSpectra then install KRLS and it works.

Presumably the intended behaviour should be to automatically resolve dependencies or fail very loudly and immediately, rather than getting to the end of the build process and failing silently?

**Comment by lukesonnet** [comment]
Hmm, that's a dependency of one of our dependencies, `rARPACK`

Thanks for the note, I'll look in to it.

**Comment by lukesonnet** [comment]
I removed these packages, and it failed noisely when I tried to install it. Not sure why R isn't following through to our dependency's dependency.

Did you already have rARPACK installed by any chance?

**Comment by chadhazlett** [comment]
I think that rARPACK was increasingly just a wrapper for RSpectra, and now
RSpectra can be used directly to get eigs(), without dependency on rARPACK.

**Comment by lukesonnet** [comment]
Ok, I'm going to switch it over to RSpectra. Should resolve this.
