### ISSUE TITLE
Warnings vs. errors in inference.krls2

### ISSUE THREAD

**Issue by lukesonnet** [lukesonnet/KRLS#10]
Currently, if someone tries to get standard errors for KRLogit without truncation, we throw a warning but still return the pwmfx and the avg pwmfx. So if you do:
`summary(krls(X=X, y=y, loss='logistic'))` 
you get a warning and no SEs but you get pwmfx. We could also error and force them to write:
`summary(krls(X=X, y=y, loss='logistic'), vcov = F)`
or we could change the default so it didn't try to get SEs without truncation, but I think that's worse than throwing the warning. So I think we currently have the right behavior, but I wanted to check.

If someone tries to get **robust or clustered** standard errors for KRLS without truncation, we throw a warning but still return the pwmfx and the avg pwmfx. So if you do:
`summary(krls(X=X, y=y), robust = T)`
you will get a warning telling you that you have to truncate, but still returning the PWMFX. The alternative is to error out, since this isn't default behavior, the user specified `robust = T` but I think the warning is sufficient. So again I think we have the right behavior, but this one I'm less sure about.

**Comment by chadhazlett** [comment]
Agreed, I like it as we have it.
