### ISSUE TITLE
Change lastkeeper to max at P for linear kernel

### ISSUE THREAD

**Issue by lukesonnet** [lukesonnet/KRLS#13]
Set this in numvectors

**Comment by lukesonnet** [comment]
Should we just warn if lastkeeper > P, and advise they set to P?

**Comment by chadhazlett** [comment]
rank(XX') should be at most P anyway so setting hard cap sound be fine.

**Comment by lukesonnet** [comment]
Okay, this currently sets max numvectors to try to P in the linear case and nrow(X) in all other cases. If for some reason it can't capture enough variance, it errors out and says that this should never happen but you can increase epsilon if you want.
