### ISSUE TITLE
KRLS compile broken on Mac.

### ISSUE THREAD

**Issue by aaronrudkin** [lukesonnet/KRLS#2]
I am sure Luke will just looooove to get this since I nagged him all day at this point, but KRLS' compile is broken on my Mac due to a missing fortran dependency of some kind. 

After a few steps of clang++ compiling, I get:
> ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-appple-darwin13.0.0/4.8.2'
> ld: library not found for -lgfortran
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [KRLS2.so] Error 1
> ERROR: compilation failed for package 'KRLS2'

Works fine in Windows 10.

**Comment by lukesonnet** [comment]
I had encountered this problem in a past iteration of this package. Not sure why it is only cropping back up now. I would like to be robust to this happening, but for now, can you try this fix?

http://stackoverflow.com/questions/36458606/rcpparmadillo-error-when-installing-package-on-mac

Edit: This appears to be a problem with Mac OS X versions, the versions of gfortran they install, and this fix is the one recommended by Eddelbuettel, the Rcpp guy.

**Comment by lukesonnet** [comment]
Pretty sure this is an Rcpp Mac OSX problem and its dealt with using the above fix described on the README for this project. Closing.
